displayName: Sensitive files blocker
type: middleware
iconPath: .assets/icon.webp

import: github.com/glefer/sensitive-files-blocker

summary: 'Middleware plugin to block sensitive files from being accessed and display a custom error page.'

testData:
  files:
    - ^.env$
    - ^.git
  template:
    enabled: true
    css: 'body { font-family: Arial, sans-serif; } h1 { color: red; }'
    html: '<html><head><title>{{ .Title }}</title></head><body><h1>{{ .Title }}</h1><p>{{ .Message }}</p></body></html>'
    vars:
      title: 'Access denied'
      message: 'You are not allowed to access this file.'
