name: Go Matrix


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    permissions:
      pull-requests: write

    strategy:
      matrix:
        go-version: [ '1.23', 1.x ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Test
        run: go test -coverprofile coverage.out ./...

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: coverage.out
          flags: unittests
          name: code-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # https://github.com/boumenot/gocover-cobertura
      - name: Install gocover-cobertura
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23'
        run: |
            go install github.com/boumenot/gocover-cobertura@latest

      - name: Convert go coverage to corbetura format
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23'
        run: gocover-cobertura < coverage.out > coverage.xml

      - name: Generate code coverage report
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23'
        with:
          recreate: true
          path: code-coverage-results.md